<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SL-1549.local" ignored="0" name="Command line test" tests="8" failures="1" timestamp="30 Dec 2020 13:59:21 GMT" time="294.785" errors="0">
  <testcase name="verifyCommentInputTest" time="47.383" classname="example.android.Tests.TextInputTest"/>
  <testcase name="verifyCommentInputTest" time="48.789" classname="example.android.Tests.TextInputTest"/>
  <testcase name="verifyCommentInputTest" time="75.575" classname="example.ios.Tests.TextInputTest"/>
  <testcase name="verifyCommentInputTest" time="117.859" classname="example.ios.Tests.TextInputTest"/>
  <testcase name="verifyLinkTest" time="39.524" classname="example.android.Tests.FollowLinkTest"/>
  <testcase name="verifyLinkTest" time="47.547" classname="example.android.Tests.FollowLinkTest"/>
  <testcase name="verifyLinkTest" time="69.962" classname="example.ios.Tests.FollowLinkTest"/>
  <testcase name="verifyLinkTest" time="71.742" classname="example.ios.Tests.FollowLinkTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at example.ios.Tests.FollowLinkTest.verifyLinkTest(FollowLinkTest.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinkTest -->
</testsuite> <!-- Command line test -->
